#!/bin/bash

echo "National Parks Region Update Script Examples"
echo "==========================================="
echo ""
echo "Before running any of these examples, replace YOUR_API_KEY with your actual OpenAI API key."
echo ""
echo "1. Test mode with 3 parks (no actual updates):"
echo "   python update_regions.py --test --limit 3 --api-key YOUR_API_KEY"
echo ""
echo "2. Test with a specific park name:"
echo "   python update_regions.py --test --name \"Yellowstone\" --api-key YOUR_API_KEY"
echo ""
echo "3. Update all parks that don't have regions:"
echo "   python update_regions.py --api-key YOUR_API_KEY"
echo ""
echo "4. Force update all parks (recalculate regions for all parks):"
echo "   python update_regions.py --force --api-key YOUR_API_KEY"
echo ""
echo "5. Use a different AI model (faster but less accurate):"
echo "   python update_regions.py --test --model gpt-3.5-turbo --api-key YOUR_API_KEY"
echo ""
echo "For more options, run:"
echo "   python update_regions.py --help" 