[build]
  command = "bash ./build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.3.0"
  NODE_ENV = "production"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Set specific versions rather than disabling
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.0"
  # Disable any automatic language installers
  NETLIFY_USE_MISE = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # Increase verbosity for debugging
  DEBUG = "netlify:*"

# Disable post-processing to eliminate another source of potential issues
[build.processing]
  skip_processing = true

# Add a deploy environment notification in case something is different in production
[context.production.environment]
  NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_CONTEXT = "deploy-preview"

# Use the custom debug plugin
[[plugins]]
  package = "./netlify-debug-plugin.js" 