# Main Netlify configuration
[build]
  command = "bash ./build-with-rollup-fix.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.3.0"
  NODE_ENV = "production"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.0"
  NETLIFY_USE_MISE = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  DEBUG = "netlify:*"
  NETLIFY = "true"
  # Add npm config directly to environment
  NPM_CONFIG_NODE_LINKER = "hoisted"

# Add a deploy environment notification in case something is different in production
[context.production.environment]
  NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_CONTEXT = "deploy-preview" 

# Force Netlify to clear cache for blog pages
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/blog"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
[[headers]]
  for = "/images/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add sitemap header to ensure correct content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# Add redirects for blog images to ensure they're found regardless of path format
[[redirects]]
  from = "/blog/images/*"
  to = "/images/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# Add debug plugin to identify blog content issues
[[plugins]]
  package = "./netlify-plugins/netlify-blog-debug-plugin.js" 