[build]
  command = "bash ./build.sh"
  publish = "dist"
  # Add a build timeout to ensure we get complete logs
  environment = { NODE_ENV = "production", CI = "true", NODE_OPTIONS = "--max-old-space-size=4096" }

[build.environment]
  NODE_VERSION = "20.3.0"
  # Disable any automatic language installers
  NETLIFY_USE_MISE = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # Disable other common potential sources of issues
  RUBY_VERSION = "false"
  PYTHON_VERSION = "false"
  # Increase verbosity for debugging
  DEBUG = "netflify:*"

# Disable post-processing to eliminate another source of potential issues
[build.processing]
  skip_processing = true

# Add a deploy environment notification in case something is different in production
[context.production.environment]
  NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_CONTEXT = "deploy-preview"

# Use the custom debug plugin
[[plugins]]
  package = "./netlify-debug-plugin.js" 