# Main Netlify configuration
[build]
  command = "bash ./build-with-rollup-fix.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.3.0"
  NODE_ENV = "production"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.0"
  NETLIFY_USE_MISE = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  DEBUG = "netlify:*"
  NETLIFY = "true"
  # Add npm config directly to environment
  NPM_CONFIG_NODE_LINKER = "hoisted"

# Add a deploy environment notification in case something is different in production
[context.production.environment]
  NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_CONTEXT = "deploy-preview" 

# Global headers to prevent caching issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Force no caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force no caching for the root path
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force Netlify to clear cache for blog pages
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/blog"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate"
    
[[headers]]
  for = "/images/blog/*"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate"

# Add sitemap header to ensure correct content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, no-cache, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Add redirects for blog images to ensure they're found regardless of path format
[[redirects]]
  from = "/blog/images/*"
  to = "/images/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# Add debug plugin to identify blog content issues
[[plugins]]
  package = "./netlify-plugins/netlify-blog-debug-plugin.js"

# Handle XML files properly
[[redirects]]
  from = "/*.xml"
  to = "/:splat"
  status = 200

# Special handling for blog post routes - serve the actual HTML files
[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug/index.html"
  status = 200
  conditions = {Country = ["!XX"]}

# Ensure root index.html is served
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# SPA fallback for non-existent routes only (this should be last and more specific)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 