# Main Netlify configuration
[build]
  command = "bash ./build-with-rollup-fix.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.3.0"
  NODE_ENV = "production"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "3.2.0"
  NETLIFY_USE_MISE = "false"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  DEBUG = "netlify:*"
  NETLIFY = "true"
  # Add npm config directly to environment
  NPM_CONFIG_NODE_LINKER = "hoisted"

# Disable post-processing to eliminate another source of potential issues
[build.processing]
  skip_processing = true

# Add a deploy environment notification in case something is different in production
[context.production.environment]
  NETLIFY_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_CONTEXT = "deploy-preview" 